apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T13:30:02Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1232"
  uid: 67e32195-09b3-44be-8166-a1b7aa3247cf
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.74.245
  clusterIPs:
  - 10.96.74.245
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30956
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
